import Page from "@/components/settings/Page";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Salkaro | Organisation",
    description: "Generated by create next app",
    robots: {
        index: false,
        follow: false,
        nocache: false,
        googleBot: {
            index: false,
            follow: false,
            noimageindex: false,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
};

export default function Settings() {
    return (
        <Page />
    );
}
